### ISSUE TITLE
Compartments with mixed N/A & 0 values

### ISSUE THREAD

**Issue by NXXR** [DLR-SC/ESID#112]
Some Compartments that currently have no values have inconsistent data, consisting of both invalid and 0 values.
I.e. `CarrierT` in the screenshot below.
Do we need to adjust our dataMap when reading from the API response to combine data into either 0 or `null`?
 
![grafik](https://user-images.githubusercontent.com/25636783/165542287-a3416466-5eb9-4be7-a334-0786a89b8fc4.png)

**Comment by PawanKaur** [comment]
0 does not mean it is NA. It could be that- there are 0 or no cases.  Missing or null values should be treated separate. A separate color code or absence of color? So 0 should remain 0 and all null/NA/missing data could be combined to one category (for example as you said null here). When visualizing it, only take 0 value frequency and leave null? Or a seperate color code for null, probably no color with boundaries.

**Comment by PawanKaur** [comment]
The current version is showing all the states with legend min and max 0 to 0

![94E6B371](https://user-images.githubusercontent.com/6088553/180453299-39806cdb-b90b-4e18-90ae-8fd29d2c9a5d.PNG)

In this figure, the legend is confusing because of min and max same value. The reason for this confusion is exponential values. As in this screenshot
![5369530](https://user-images.githubusercontent.com/6088553/180453711-7a7f9429-3056-42d3-a8c0-87172a618087.PNG)

And legend is doing right and showing the division of 0


So what are the options to have more reliable legend. 

1) On the legend, show min and max values as 0 to 0.000000654.
2) Auto hide the legend when min and max values are 0. 
3) Have something like in the US map above. Showing only the border of the map without color.

**Comment by PawanKaur** [comment]
> Some Compartments that currently have no values have inconsistent data, consisting of both invalid and 0 values. I.e. `CarrierT` in the screenshot below. Do we need to adjust our dataMap when reading from the API response to combine data into either 0 or `null`?
> 
> ![grafik](https://user-images.githubusercontent.com/25636783/165542287-a3416466-5eb9-4be7-a334-0786a89b8fc4.png)


The problem is with line [217](https://github.com/DLR-SC/ESID/blob/develop/frontend/src/components/Sidebar/DistrictMap.tsx#L217)
![image](https://user-images.githubusercontent.com/6088553/184918722-dc75a7dc-17f5-4b82-9f68-e9ad9b177e9a.png)

If there is no data for the available district, it put NaN. If I change it to 0, the error disappears.

**Comment by PawanKaur** [comment]
Yea. Just a note, these values are 0 which are being assigned NaN![Unbenannt.png](https://images.zenhubusercontent.com/629724aa25e0d856f149e9b2/2574bae0-8f83-4e63-84df-00e4793fcbc2)
